#!/usr/bin/env python3
import sys
sys.path.insert(0, '/home/orangepi/scuderiaferrari/install/track_perception/lib/python3.10/site-packages')
from track_perception_python.perception_decision_node import main
main()
